name             'sssd'
maintainer       'Localytics'
maintainer_email 'oss@localytics.com'
license          'Apache 2.0'
description      'Installs/Configures sssd for use with an AD backend such as Amazon DS'
long_description 'Installs/Configures sssd for use with an AD backend such as Amazon DS'
version          '0.2.0'

depends 'apt', '~> 2.7.0'
depends 'resolver', '~> 1.2.0'
depends 'yum', '~> 3.5.0'
depends 'yum-epel', '~> 0.6.0'
